### ISSUE TITLE
Pre-parsing?

### ISSUE THREAD

**Issue by dovy** [kaliatech/dygraphs-dynamiczooming-example#3]
I'm looking at a huge series of like 32,962 entries to plot per graph. Loading this all into JS is not exactly feasible.

Do you have any suggestions on how to implement this same functionality server-side, while allowing the user to view the data?

**Comment by kaliatech** [comment]
Loading, parsing, and drawing 32k points in JavaScript is not necessarily too much depending on data structure and how many points you need to draw on screen at one time.  You haven't provided enough info.

If your data is truly too large to handle client side, then on the client you could use the approach I explained in this repo.  On the server side, you could preparse the data in to digestable intervals (assuming it can all be held in memory). Or if the data is time based, you could store the data in a time-series database which would make querying for arbitrary intervals fast and easy.
