### ISSUE TITLE
Data Annotations issues

### ISSUE THREAD

**Issue by jjimenezroda** [kaliatech/dygraphs-dynamiczooming-example#4]
Data Annotations does not really work when splicing the data, since the ranges might be very different  on the scale. Is there a plan or way to fix it?

Thanks.

**Comment by kaliatech** [comment]
It's not clear what you mean. Annotations are added as a separate data set.  How the annotations are retrieved is use-case dependent and outside of the scope of dygraphs.  To show that annotations work fine with the dynamic zooming technique presented in this repo, I added example #7:
 * https://kaliatech.github.io/dygraphs-dynamiczooming-example/example7.html

The example starts off with an annotations added for every month, but if you change range to 1d, it adds annotations for every hour.
