### ISSUE TITLE
Integrating into R environment

### ISSUE THREAD

**Issue by woec** [kaliatech/dygraphs-dynamiczooming-example#5]
Hi,

I find the examples presented here very impressive and interesting. 
I created a shiny server application which uses dygraph to present huge amount of multiple data series to a browser access.
The methods described here would help  to reduce the waiting times for the user, when working on the graphs (zooming, panning etc).
But I am not familiar with javascript.
Is there a easy way to integrate your methods into the R environment without heavily use of javascript?

Regards,
woec

**Comment by kaliatech** [comment]
It is not clear what you are asking. I do not have a lot of experience with R. I suppose you have already seen libraries like this one:
- https://rstudio.github.io/dygraphs/index.html

At a high level, the techniques I presented should work anywhere. (Specifically, combining dense and sparse data sets in to one master data set that can be used by dygraphs). Beyond that though, I think it's highly dependent on what exactly you are trying to do, and how you are incorporating dygraphs.
